### ISSUE TITLE
Figure out what is up with montat and perez

### ISSUE THREAD

**Issue by adriansteffan** [peekbank/peekbank-data-import#125]
These might be subsets of each other, figure out what is up here and upload the dataset to osf (links in the dataset sheet here https://docs.google.com/spreadsheets/d/1nGXWRu6_q7ATGrdWrFDuDmb9VoGHCnTO9NLhqhpuN28/edit#gid=0)

**Comment by alvinwmtan** [comment]
Should also double-check with byers-heinlein_2017 (from same lab)

**Comment by alvinwmtan** [comment]
Checked. perez_2024 is a strict subset of montat_2022; we should only import the latter. byers-heinlein_2017 does not overlap with either.

**Comment by alvinwmtan** [comment]
CORRECTION: byers-heinlein_2017 is also a subset of montat_2022. Will investigate more; if needed I will update the data.
