### ISSUE TITLE
Validators for bilinguals: comma separated iso values

### ISSUE THREAD

**Issue by adriansteffan** [peekbank/peekbank-data-import#135]
fix both validators to allow for this
IMPORTANT

**Comment by adriansteffan** [comment]
This was already the case, nvm

**Comment by alvinwmtan** [comment]
Figured it out—the validated set of ISO codes are ISO 639-2B and I used ISO 639-3 codes haha. We may possibly consider switching to 639-3 in the future because it's more comprehensive.
