### ISSUE TITLE
Standardize stimulus_image_path

### ISSUE THREAD

**Issue by benpry** [peekbank/peekbank-data-import#141]
Some datasets have stimulus_image_path as just a file name (Adams and Marchman), others are paths starting at the raw_data folder, others are paths starting at a sub-folder of raw_data path.

The correct format is starting at raw_data.

**Comment by adriansteffan** [comment]
I went over all of the datasets and standardized the image paths using a new step in the validator. We should now be able to trust that every stimulus_image_path (that is not NA) actually points to an existing file starting from raw_data
