### ISSUE TITLE
[nordmeyer_negtracker_2014] Update import script to match 2024 schema (reorg raw data?)

### ISSUE THREAD

**Issue by adriansteffan** [peekbank/peekbank-data-import#60]
format seems to be quite old (rmd)

The data seems to be missing from osf entirely (?)

**Comment by mzettersten** [comment]
Yes, this will sometimes be the case for datasets that have not been worked on yet. All of the various newman lab datasets are organized here: https://drive.google.com/drive/folders/1XW_xNodQGwYUadcjopBV2zj2jSVFFKzw?usp=sharing

**Comment by adriansteffan** [comment]
So Martin renamed the folder on OSF, and there is more data to be found on this drive: https://drive.google.com/drive/folders/1UbGrZPVQlAlL6PZa3NGYT26a-yaS8krg?usp=sharing (uploaded by mike)

Mike said the following in a related issue:

> Note that this is the original archival folder. The readme explains that only "version 5" is published in the paper, and that's the one we should import. it's represented in the paper as two experiments, but was run as a single package. please feel free to tag me with comments if you have questions.

This dataset will need a closer look to identify all the needed data

**Comment by adriansteffan** [comment]
@mzettersten 
This one needs another look during a meeting, might be easier to tackle it together:

The datafiles have a different structure from what the existing import script assumes and I am currently missing the link between the eyetracking timepoints and the trials.

There is also the discussion about how to represent the negation trials in the stimuli. I think we reached a conclusion here some time ago, but I think we forgot to document it.

**Comment by adriansteffan** [comment]
These specific issues have been resolved, so refer to the corresponding import issue for further discussion on this dataset
